#Problem 2 from projecteuler.net
#Author: Blair Gemmer
"""Description of Problem 2, Even Fibonacci numbers:
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
from math import *

def fib(n):
    return int(((1+sqrt(5))**n-(1-sqrt(5))**n)/(2**n*sqrt(5)))


start = 0
end = 42
evenFibs = []

for i in map (fib, range(start, end)):
    if (i < 4000000 and i % 2 == 0): #if less than 4 million and even:
        evenFibs.append(i)

print sum(evenFibs)    
